name: Pull Request

on:
  pull_request:
    types:
      - closed

permissions:
  contents: write

env:
  NODE_VERSION: 18.16.0

jobs:
  if_merged:
    if: github.event.pull_request.merged == true
    name: Build And Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout️
        uses: actions/checkout@v3

      - name: Setup Continuous integration
        uses: ./.github/actions/ci-setup

      - name: Build
        run: npm run build

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist
