name: Pull Request

on:
  pull_request:
    types: [opened, synchronize]

env:
  NODE_VERSION: 21.5.0

jobs:
  linting:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Continuous integration
        uses: ./.github/actions/ci-setup

      - name: Lint Application
        run: npm run lint

  type-check:
    name: Types
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Continuous Integration
        uses: ./.github/actions/ci-setup

      - name: Check Application Types
        run: npm run type-check
        
  prettify:
    name: Prettier
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3
  
      - name: Setup Continuous Integration
        uses: ./.github/actions/ci-setup
  
      - name: Check Application Types
        run: npm run prettier:fix

  # tests:
  #   name: Test
  #   runs-on: ubuntu-latest

  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v3
        
  #     - name: Npm Clean Install
  #       run: npm ci

  #     - name: test
  #       run: npm run test
